version: '2'
services:
  mailer:
    build: ../../
    restart: always
    container_name: mailer
    network_mode: "host"
    environment:
      - MAILER_ENVIRONMENT=staging
    volumes:
      - ../../../:/mailer